package telas;

import conexao.Conexao;
import dao.ClienteDao;
import dao.EstoqueDao;
import dao.LocacaoDao;
import entidade.Cliente;
import entidade.Estoque;
import entidade.Locacao;
import java.sql.*;
import java.util.List;
import javax.swing.*;



public class CadLocacao extends javax.swing.JFrame {

    Connection conexao;
    PreparedStatement linguagem;
    
   


    public CadLocacao() {
        initComponents();
        conexao = Conexao.conexao();
        PreparedStatement stmt = null;

    }

    private void preenche_combo(){      
        Cliente c = new Cliente();
        ClienteDao daoC = new ClienteDao();
        List<Cliente> cliente = daoC.PreencheCliente();
       
        for(Cliente cli: cliente){
           
        jcliente.addItem(cli.getNomeCliente());
           
        }
        
        Estoque e = new Estoque();
        EstoqueDao daoR = new EstoqueDao();
        List<Estoque> estoque = daoR.PreencheEstoque();
       
        for(Estoque rou: estoque){
           
        jroupa.addItem(rou.getNomeRoupa());
           
        }
     
     }

    
  void novo(){
      
      jcliente.setEnabled(true);
      jroupa.setEnabled(true);
      jdataLocacao.setEnabled(true);
      jdataDevolucao.setEnabled(true);
      jobservacao.setEnabled(true);
      jvalor.setEnabled(true);
      jcadastrar.setEnabled(true);
      preenche_combo();
  }
  
  void limpar(){
      jdataLocacao.setText("");
      jdataDevolucao.setText("");
      jobservacao.setText("");
      jvalor.setText("");

  }
   
   void cadastrar(){
        try{
            //Instância do Locação;
            LocacaoDao dao = new LocacaoDao();
            Locacao l = new Locacao();
            
            //Instância de Cliente e Estoque;
            ClienteDao daoC = new ClienteDao();   
            Cliente c = new Cliente();
            
            EstoqueDao daoE = new EstoqueDao();   
            Estoque e = new Estoque();
            
            
            //1ºCria variável e atribui o item selecionado da JComboBox;
            //2ºInsere o nome atribuido na variável dentro de Cliente;
            //3ºUtiliza o método criado no DAO;
            
            String cli = (String)jcliente.getSelectedItem();
            c.setNomeCliente(cli);            
            daoC.buscanome(c);
            
            String roupa = (String)jroupa.getSelectedItem();
            e.setNomeRoupa(roupa);
            daoE.buscanomeR(e);
            
            /*Teste de Recebimento de ID's;
            
            JOptionPane.showMessageDialog(null, c.getIdCliente());
            JOptionPane.showMessageDialog(null, c.getNomeCliente());
            JOptionPane.showMessageDialog(null, e.getIdRoupa());
            JOptionPane.showMessageDialog(null, e.getNomeRoupa());*/

            
            //CADASTRO;
            l.setIdCliente(c.getIdCliente());
            l.setIdRoupa(e.getIdRoupa());
            l.setDataLocacao(jdataLocacao.getText());
            l.setDataDevolucao(jdataDevolucao.getText());
            l.setObservacao(jobservacao.getText());
            l.setValorTotal(Double.parseDouble(jvalor.getText()));
            
            dao.adicionar(l);
            JOptionPane.showMessageDialog(null,"Locação Cadastrada!");
            limpar();
            
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Erro ao cadastrar Locação "+e.getMessage());
    }
    }
    

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdataLocacao = new javax.swing.JFormattedTextField();
        jdataDevolucao = new javax.swing.JFormattedTextField();
        jobservacao = new javax.swing.JTextField();
        jvalor = new javax.swing.JFormattedTextField();
        jcliente = new javax.swing.JComboBox<>();
        jroupa = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jmenu = new javax.swing.JButton();
        jnovo = new javax.swing.JButton();
        jsair = new javax.swing.JButton();
        jcadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setMinimumSize(new java.awt.Dimension(550, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        try {
            jdataLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdataLocacao.setEnabled(false);
        getContentPane().add(jdataLocacao);
        jdataLocacao.setBounds(200, 150, 104, 30);

        try {
            jdataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdataDevolucao.setEnabled(false);
        getContentPane().add(jdataDevolucao);
        jdataDevolucao.setBounds(200, 190, 104, 30);

        jobservacao.setEnabled(false);
        getContentPane().add(jobservacao);
        jobservacao.setBounds(200, 230, 170, 30);

        jvalor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jvalor.setEnabled(false);
        getContentPane().add(jvalor);
        jvalor.setBounds(200, 270, 100, 30);

        getContentPane().add(jcliente);
        jcliente.setBounds(200, 70, 237, 20);

        getContentPane().add(jroupa);
        jroupa.setBounds(200, 110, 237, 20);

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CADASTRO DE LOCAÇÃO");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 10, 210, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cliente:");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 70, 150, 24);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Roupa:");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 110, 150, 24);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Data de Locação:");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 150, 150, 24);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Data de Devolução:");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 190, 150, 24);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Valor Total:");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 270, 150, 24);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Observação:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 230, 150, 24);

        jmenu.setText("Menu");
        jmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        getContentPane().add(jmenu);
        jmenu.setBounds(460, 70, 50, 19);

        jnovo.setText("Novo");
        jnovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jnovo);
        jnovo.setBounds(460, 100, 50, 19);

        jsair.setText("Sair");
        jsair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsairActionPerformed(evt);
            }
        });
        getContentPane().add(jsair);
        jsair.setBounds(410, 340, 50, 19);

        jcadastrar.setText("Cadastrar");
        jcadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jcadastrar);
        jcadastrar.setBounds(240, 340, 90, 19);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -20, 540, 400);

        jMenuBar1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem6.setText("Sair");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CadCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuActionPerformed

    private void jnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnovoActionPerformed
        novo();
    }//GEN-LAST:event_jnovoActionPerformed

    private void jsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jsairActionPerformed

    private void jcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jcadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jcadastrar;
    private javax.swing.JComboBox<Object> jcliente;
    private javax.swing.JFormattedTextField jdataDevolucao;
    private javax.swing.JFormattedTextField jdataLocacao;
    private javax.swing.JButton jmenu;
    private javax.swing.JButton jnovo;
    private javax.swing.JTextField jobservacao;
    private javax.swing.JComboBox<Object> jroupa;
    private javax.swing.JButton jsair;
    private javax.swing.JFormattedTextField jvalor;
    // End of variables declaration//GEN-END:variables

   

}


