package telas;

import entidade.Cliente;
import dao.ClienteDao;
import conexao.Conexao;
import dao.FuncionarioDao;
import entidade.Funcionario;
import java.sql.*;
import javax.swing.*;

public class ConsultarFuncionario extends javax.swing.JFrame {

    Connection conexao;
    PreparedStatement linguagem;
    ResultSet linha;

    void novo() {
        jcpf.setEnabled(true);
        jconsultar.setEnabled(true);
        jcpf.requestFocus();
    }

    void limpar() {
        jcpf.setText("");
        jnome.setText("");
        jdataNasc.setText("");
        jdataAdm.setText("");
        jcodigo.setText("");
        jtelefone.setText("");
        jendereco.setText("");
        jemail.setText("");
        jcpf.requestFocus();
    }

    public ConsultarFuncionario() {
        initComponents();
        conexao = Conexao.conexao();

    }

    void consultar() {
        try {
            String cpfFuncionario = jcpf.getText();
            FuncionarioDao dao = new FuncionarioDao();
            Funcionario funcionario = dao.consultar(cpfFuncionario);
            if (funcionario == null) {
                JOptionPane.showMessageDialog(null, "Funcionário não Encontrado");
                limpar();
            }else{
                jcodigo.setText(String.valueOf(funcionario.getIdFuncionario()));
                jnome.setText(funcionario.getNomeFuncionario());
                jdataNasc.setText(funcionario.getDataNascimentoFuncionario());
                jdataAdm.setText(funcionario.getDataAdmissao());
                jcpf.setText(funcionario.getCpfFuncionario());
                jendereco.setText(funcionario.getEnderecoFuncionario());
                jtelefone.setText(String.valueOf(funcionario.getTelefoneFuncionario()));
                jemail.setText(funcionario.getEmailFuncionario());
                
                JOptionPane.showMessageDialog(null,"Funcionário encontrado");
                jeditar.setEnabled(true);
                jsalvar.setEnabled(true);
                jexcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro no SQL" + e.getMessage());
        }
    }
    
    void editar(){
        jnome.setEnabled(true);
        jdataNasc.setEnabled(true);
        jdataAdm.setEnabled(true);
        jendereco.setEnabled(true);
        jtelefone.setEnabled(true);
        jemail.setEnabled(true);
    }
    
    void salvar(){
        String cpf = jcpf.getText();
        String nome = jnome.getText();
        String dataN = jdataNasc.getText();
        String dataAdm = jdataAdm.getText();
        String endereco = jendereco.getText();
        String telefone = jtelefone.getText();
        String email = jemail.getText();
        
        Funcionario funcionario = new Funcionario();
        
        funcionario.setCpfFuncionario(cpf);
        funcionario.setNomeFuncionario(nome);
        funcionario.setDataNascimentoFuncionario(dataN);
        funcionario.setDataAdmissao(dataAdm);
        funcionario.setEnderecoFuncionario(endereco);
        funcionario.setTelefoneFuncionario(telefone);
        funcionario.setEmailFuncionario(email);
        
        FuncionarioDao dao = new FuncionarioDao();
        dao.atualizar(funcionario);
        JOptionPane.showMessageDialog(null, "Funcionário Atualizado!");
        limpar();
        jnome.setEnabled(false);
        jdataNasc.setEnabled(false);
        jdataAdm.setEnabled(false);
        jendereco.setEnabled(false);
        jtelefone.setEnabled(false);
        jemail.setEnabled(false);
        
    }
    void excluir(){
        FuncionarioDao dao = new FuncionarioDao();
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Excluir?", "Exclusão",JOptionPane.YES_NO_OPTION);
        if(confirma ==JOptionPane.YES_OPTION){
            dao.excluir(jcpf.getText());
            JOptionPane.showMessageDialog(null,"Funcionário Excluído!");
            limpar();
        }else{jcpf.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdataAdm = new javax.swing.JTextField();
        jdataNasc = new javax.swing.JTextField();
        jendereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcpf = new javax.swing.JFormattedTextField();
        jcodigo = new javax.swing.JTextField();
        jtelefone = new javax.swing.JFormattedTextField();
        jnome = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jconsultar = new javax.swing.JButton();
        jsair = new javax.swing.JButton();
        jexcluir = new javax.swing.JButton();
        jsalvar = new javax.swing.JButton();
        jeditar = new javax.swing.JButton();
        jnovo = new javax.swing.JButton();
        jmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Cliente");
        setMinimumSize(new java.awt.Dimension(513, 477));
        setResizable(false);
        getContentPane().setLayout(null);

        jdataAdm.setEnabled(false);
        jdataAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdataAdmActionPerformed(evt);
            }
        });
        getContentPane().add(jdataAdm);
        jdataAdm.setBounds(210, 230, 184, 30);

        jdataNasc.setEnabled(false);
        getContentPane().add(jdataNasc);
        jdataNasc.setBounds(210, 190, 184, 30);

        jendereco.setEnabled(false);
        jendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jendereco);
        jendereco.setBounds(210, 270, 184, 30);

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CONSULTAR FUNCIONÁRIO");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 10, 220, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Código:");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 110, 150, 24);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nome:");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 150, 150, 24);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CPF:");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 60, 150, 24);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data de Admissão:");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 230, 150, 24);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Telefone:");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 310, 150, 24);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Email:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 350, 150, 24);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Endereço:");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 270, 150, 24);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Data de Nascimento:");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 190, 150, 24);

        try {
            jcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcpf.setEnabled(false);
        jcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcpfActionPerformed(evt);
            }
        });
        getContentPane().add(jcpf);
        jcpf.setBounds(210, 60, 169, 30);

        jcodigo.setEditable(false);
        jcodigo.setEnabled(false);
        getContentPane().add(jcodigo);
        jcodigo.setBounds(210, 110, 50, 30);

        try {
            jtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtelefone.setEnabled(false);
        getContentPane().add(jtelefone);
        jtelefone.setBounds(210, 310, 130, 30);

        jnome.setEnabled(false);
        getContentPane().add(jnome);
        jnome.setBounds(210, 150, 169, 30);

        jemail.setEnabled(false);
        getContentPane().add(jemail);
        jemail.setBounds(210, 350, 169, 30);

        jconsultar.setText("Consultar");
        jconsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jconsultar.setEnabled(false);
        jconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jconsultar);
        jconsultar.setBounds(250, 390, 70, 19);

        jsair.setText("Sair");
        jsair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsairActionPerformed(evt);
            }
        });
        getContentPane().add(jsair);
        jsair.setBounds(430, 390, 50, 19);

        jexcluir.setText("Excluir");
        jexcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jexcluir.setEnabled(false);
        jexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jexcluir);
        jexcluir.setBounds(430, 250, 50, 19);

        jsalvar.setText("Salvar");
        jsalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jsalvar.setEnabled(false);
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jsalvar);
        jsalvar.setBounds(430, 190, 50, 19);

        jeditar.setText("Editar");
        jeditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jeditar.setEnabled(false);
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });
        getContentPane().add(jeditar);
        jeditar.setBounds(430, 160, 50, 19);

        jnovo.setText("Novo");
        jnovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jnovo);
        jnovo.setBounds(430, 100, 50, 19);

        jmenu.setText("Menu");
        jmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        getContentPane().add(jmenu);
        jmenu.setBounds(430, 70, 50, 19);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -20, 520, 460);

        jMenuBar1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem6.setText("Sair");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jdataAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdataAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdataAdmActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CadCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenderecoActionPerformed

    private void jcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcpfActionPerformed

    private void jconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconsultarActionPerformed
        consultar();
    }//GEN-LAST:event_jconsultarActionPerformed

    private void jsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jsairActionPerformed

    private void jexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexcluirActionPerformed
        excluir();
    }//GEN-LAST:event_jexcluirActionPerformed

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
        salvar();
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
        editar();
    }//GEN-LAST:event_jeditarActionPerformed

    private void jnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnovoActionPerformed
        novo();
    }//GEN-LAST:event_jnovoActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JButton jconsultar;
    private javax.swing.JFormattedTextField jcpf;
    private javax.swing.JTextField jdataAdm;
    private javax.swing.JTextField jdataNasc;
    private javax.swing.JButton jeditar;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jendereco;
    private javax.swing.JButton jexcluir;
    private javax.swing.JButton jmenu;
    private javax.swing.JTextField jnome;
    private javax.swing.JButton jnovo;
    private javax.swing.JButton jsair;
    private javax.swing.JButton jsalvar;
    private javax.swing.JFormattedTextField jtelefone;
    // End of variables declaration//GEN-END:variables

   

   

}
