package telas;

import conexao.Conexao;
import dao.LocacaoDao;
import entidade.Locacao;
import java.sql.*;
import javax.swing.*;



public class ConsultarLocacao extends javax.swing.JFrame {

    Connection conexao;
    PreparedStatement linguagem;


    public ConsultarLocacao() {
        initComponents();
        conexao = Conexao.conexao();
        PreparedStatement stmt = null;

    }

    
  void novo(){
      jdataLocacao.setEnabled(true);
      jconsultar.setEnabled(true);
  }
  
  void limpar(){
      jcliente.setText("");
      jroupa.setText("");
      jdataLocacao.setText("");
      jdataDevolucao.setText("");
      jobservacao.setText("");
      jvalor.setText("");

  }
    
  void consultar() {
        try {
            String dl = jdataLocacao.getText();
            LocacaoDao dao = new LocacaoDao();
            Locacao locacao = dao.consultar(dl);

            if (dl == null) {
                JOptionPane.showMessageDialog(null, "Locação não encontrada!");
                limpar();
            }else{
                jcliente.setText(String.valueOf(locacao.getIdCliente()));
                jroupa.setText(String.valueOf(locacao.getIdRoupa()));
                jdataLocacao.setText(locacao.getDataLocacao());
                jdataDevolucao.setText(locacao.getDataDevolucao());
                jobservacao.setText(locacao.getObservacao());
                jvalor.setText(String.valueOf(locacao.getValorTotal()));
                jeditar.setEnabled(true);
                jsalvar.setEnabled(true);
                jexcluir.setEnabled(true);
                
                JOptionPane.showMessageDialog(null,"Locação encontrada!");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "erro no SQL " + e.getMessage());
        }
    }
  
  void salvar(){

        String dataL = jdataLocacao.getText();
        String dataD = jdataDevolucao.getText();
        String observacao = jobservacao.getText();
        Double valor = Double.parseDouble(jvalor.getText());
        
        Locacao locacao = new Locacao();
        
        locacao.setDataLocacao(dataL);
        locacao.setDataDevolucao(dataD);
        locacao.setObservacao(observacao);
        locacao.setValorTotal(valor);

        LocacaoDao dao = new LocacaoDao();
        dao.atualizar(locacao);
        JOptionPane.showMessageDialog(null, "Locação atualizada!");
        limpar();
        jdataDevolucao.setEnabled(false);
        jobservacao.setEnabled(false);
        jvalor.setEnabled(false);
        jdataLocacao.requestFocus();
        
    }
    
    void editar(){
    jdataDevolucao.setEnabled(true);
    jobservacao.setEnabled(true);
    jvalor.setEnabled(true);
}
    
    
    void excluir(){
        LocacaoDao dao = new LocacaoDao();
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Excluir?", "Exclusão",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            dao.excluir(jdataLocacao.getText());
            JOptionPane.showMessageDialog(null,"Excluído");
            limpar();
        }else{jdataLocacao.requestFocus();
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jvalor = new javax.swing.JFormattedTextField();
        jobservacao = new javax.swing.JTextField();
        jdataDevolucao = new javax.swing.JFormattedTextField();
        jdataLocacao = new javax.swing.JFormattedTextField();
        jmenu = new javax.swing.JButton();
        jnovo = new javax.swing.JButton();
        jeditar = new javax.swing.JButton();
        jsalvar = new javax.swing.JButton();
        jexcluir = new javax.swing.JButton();
        jsair = new javax.swing.JButton();
        jconsultar = new javax.swing.JButton();
        jcliente = new javax.swing.JTextField();
        jroupa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setMinimumSize(new java.awt.Dimension(513, 477));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CONSULTAR LOCAÇÃO");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 10, 210, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cliente:");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 110, 150, 24);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Roupa:");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 150, 150, 24);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Data de Locação:");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 60, 150, 24);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Data de Devolução:");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 190, 150, 24);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Observação:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 230, 150, 24);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Valor Total:");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 270, 150, 24);

        jvalor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jvalor.setEnabled(false);
        getContentPane().add(jvalor);
        jvalor.setBounds(210, 270, 100, 30);

        jobservacao.setEnabled(false);
        getContentPane().add(jobservacao);
        jobservacao.setBounds(210, 230, 170, 30);

        try {
            jdataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdataDevolucao.setEnabled(false);
        getContentPane().add(jdataDevolucao);
        jdataDevolucao.setBounds(210, 190, 104, 30);

        try {
            jdataLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdataLocacao.setEnabled(false);
        getContentPane().add(jdataLocacao);
        jdataLocacao.setBounds(210, 60, 104, 30);

        jmenu.setText("Menu");
        jmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        getContentPane().add(jmenu);
        jmenu.setBounds(430, 70, 50, 19);

        jnovo.setText("Novo");
        jnovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jnovo);
        jnovo.setBounds(430, 100, 50, 19);

        jeditar.setText("Editar");
        jeditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jeditar.setEnabled(false);
        jeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditarActionPerformed(evt);
            }
        });
        getContentPane().add(jeditar);
        jeditar.setBounds(430, 160, 50, 19);

        jsalvar.setText("Salvar");
        jsalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jsalvar.setEnabled(false);
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jsalvar);
        jsalvar.setBounds(430, 190, 50, 19);

        jexcluir.setText("Excluir");
        jexcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jexcluir.setEnabled(false);
        jexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jexcluir);
        jexcluir.setBounds(430, 250, 50, 19);

        jsair.setText("Sair");
        jsair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsairActionPerformed(evt);
            }
        });
        getContentPane().add(jsair);
        jsair.setBounds(430, 390, 50, 19);

        jconsultar.setText("Consultar");
        jconsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jconsultar.setEnabled(false);
        jconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jconsultar);
        jconsultar.setBounds(250, 390, 70, 19);

        jcliente.setEnabled(false);
        getContentPane().add(jcliente);
        jcliente.setBounds(210, 110, 170, 30);

        jroupa.setEnabled(false);
        getContentPane().add(jroupa);
        jroupa.setBounds(210, 150, 170, 30);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -30, 520, 480);

        jMenuBar1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem6.setText("Sair");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuActionPerformed

    private void jnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnovoActionPerformed
        novo();
    }//GEN-LAST:event_jnovoActionPerformed

    private void jeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditarActionPerformed
        editar();
    }//GEN-LAST:event_jeditarActionPerformed

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
        salvar();
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexcluirActionPerformed
       excluir();
    }//GEN-LAST:event_jexcluirActionPerformed

    private void jsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jsairActionPerformed

    private void jconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconsultarActionPerformed
        consultar();
    }//GEN-LAST:event_jconsultarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CadCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jcliente;
    private javax.swing.JButton jconsultar;
    private javax.swing.JFormattedTextField jdataDevolucao;
    private javax.swing.JFormattedTextField jdataLocacao;
    private javax.swing.JButton jeditar;
    private javax.swing.JButton jexcluir;
    private javax.swing.JButton jmenu;
    private javax.swing.JButton jnovo;
    private javax.swing.JTextField jobservacao;
    private javax.swing.JTextField jroupa;
    private javax.swing.JButton jsair;
    private javax.swing.JButton jsalvar;
    private javax.swing.JFormattedTextField jvalor;
    // End of variables declaration//GEN-END:variables

   

}


